# Generated by Django 3.2.5 on 2021-07-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testt', '0003_auto_20210721_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testt',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Testt',
        ),
    ]
